Repository strongloop/loopback.io, pull requests merged in 2018-04, with the labels that each got.

#657 refactor: remove refactored files
  update-v4-readmes.sh
Labels: #review, review

#662 Warning about form parsers
  pages/en/lb3/Storage-component.md
Labels: #review, review

#663 Add warning about multipart parsers
  pages/en/lb3/Storage-component.md
Labels: #review, needs-priority

#665 update LB4 release name
  _includes/content/v4notice.html
  doc/index.md
Labels: #review, review

#666 chore: add build script
  package.json
  update-lb4-docs.js
Labels: #review, review

#672 chore: update Gemfile.lock and package.json
  Gemfile.lock
  package.json
Labels: #review, review

#670 lb3: improve Model Discovery docs
  pages/en/lb3/Discovering-models-from-relational-databases.md
Labels: customer
